import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { supabaseAdmin } from "@/lib/supabase";
import { decryptSecret } from "@/lib/crypto";
import { rateLimit } from "@/lib/rate-limit";
const bodySchema=z.object({messages:z.array(z.object({role:z.enum(["user","assistant"]),content:z.string().max(2000)})).min(1).max(30)});
const basePrompt="You are the concise, professional guide for Mehedi's personal portfolio. Describe Mehedi as an independent AI & Automation Specialist with 2+ years of hands-on experience and 1+ year of client delivery. Explain his AI agents, workflow automation, CRM/outreach systems and SaaS MVP capabilities. Known work: 13+ workflow gaming venue member lifecycle; Gazi AI outreach SaaS; eight-agent UK skincare ecosystem. Never present him as an agency or team. Never invent results, testimonials, prices or guarantees. Ask one useful discovery question at a time. Suggest the contact form for project, contract or employment opportunities.";
async function callProvider(provider:string,key:string,model:string,prompt:string,messages:{role:string;content:string}[],temperature:number,maxTokens:number){
 if(provider==="anthropic"){const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"content-type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01"},body:JSON.stringify({model,max_tokens:maxTokens,temperature,system:prompt,messages})});if(!r.ok)throw new Error("Provider failed");const d=await r.json();return d.content?.[0]?.text as string}
 if(provider==="gemini"){const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({system_instruction:{parts:[{text:prompt}]},contents:messages.map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]})),generationConfig:{temperature,maxOutputTokens:maxTokens}})});if(!r.ok)throw new Error("Provider failed");const d=await r.json();return d.candidates?.[0]?.content?.parts?.[0]?.text as string}
 const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature,max_tokens:maxTokens,messages:[{role:"system",content:prompt},...messages]})});if(!r.ok)throw new Error("Provider failed");const d=await r.json();return d.choices?.[0]?.message?.content as string
}
function localReply(question:string){const q=question.toLowerCase();if(q.includes("who are you")||q.includes("your name"))return "I’m the AI guide for Mehedi’s personal portfolio. I can explain his experience, projects and technical skills, or help you decide whether he’s a good fit for a project or role.";if(q.includes("eight")||q.includes("skincare")||q.includes("agent"))return "Mehedi designed the UK skincare system around eight task-specific AI agents with shared business knowledge, centralized data and n8n workflows on self-hosted infrastructure. The key design idea was orchestration—not one oversized chatbot.";if(q.includes("saas"))return "Yes. Mehedi combines Next.js interfaces, databases, APIs and automation engines into client-facing SaaS MVPs. Gazi AI is the flagship example: sourcing, enrichment, personalized sequences and campaign tracking in one platform.";return "Mehedi builds AI agents, n8n/Make/Zapier workflows, CRM and outreach systems, API integrations, dashboards and SaaS MVPs. He is available for selected freelance, contract and full-time opportunities. What would you like to know about his work?"}
export async function POST(req:NextRequest){const ip=req.headers.get("x-forwarded-for")||"local";if(!rateLimit(`ai:${ip}`,20,60000))return NextResponse.json({error:"Please wait a moment"},{status:429});try{const {messages}=bodySchema.parse(await req.json());let message="",used="local",model="knowledge-fallback";try{const db=supabaseAdmin(),settingsResult=await db.from("app_settings").select("data").eq("key","ai:main").maybeSingle(),settings=settingsResult.data?.data||{},order=[settings.activeProvider,...(settings.fallbackProviders||[])].filter(Boolean) as string[],configRows=await db.from("app_settings").select("key,data").in("key",order.map(provider=>`provider:${provider}`)),configs=(configRows.data||[]).map(row=>row.data);for(const provider of order){const c=configs.find(item=>item?.provider===provider);if(!c?.encryptedApiKey||!c.enabled)continue;try{model=c.model||settings.model||"gpt-4.1-mini";const prompt=`${settings.systemPrompt||basePrompt}\n\nThis is Mehedi’s personal portfolio. Refer to its public identity as Mehedi / AI and never call it NexaFlow.`;message=await callProvider(provider,decryptSecret(c.encryptedApiKey),model,prompt,messages,settings.temperature??.3,settings.maxTokens??500);used=provider;break}catch{continue}}if(!message)message=localReply(messages.at(-1)?.content||"");await db.from("cms_documents").insert({collection:"aiConversations",data:{sessionId:crypto.randomUUID(),messages:[...messages,{role:"assistant",content:message}],provider:used,model},status:"complete",visible:false})}catch{message=localReply(messages.at(-1)?.content||"")}return NextResponse.json({message,provider:used})}catch{return NextResponse.json({error:"Invalid chat request"},{status:400})}}
