"use client";

import { useEffect, useState } from "react";
import { Bot, LoaderCircle, Save, TestTube2 } from "lucide-react";

type Form = { activeProvider: "openai" | "anthropic" | "gemini"; model: string; apiKey: string; systemPrompt: string; temperature: number; maxTokens: number; monthlyLimit: number; leadQualification: boolean; bookingEnabled: boolean; fallbackEnabled: boolean };
const initial: Form = { activeProvider: "openai", model: "gpt-4.1-mini", apiKey: "", systemPrompt: "You are the concise, professional guide for Mehedi’s personal portfolio. Never invent results or guarantees.", temperature: .3, maxTokens: 500, monthlyLimit: 0, leadQualification: true, bookingEnabled: true, fallbackEnabled: true };

export function AISettingsForm() {
  const [form, setForm] = useState<Form>(initial);
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/admin/ai-settings").then(response => response.ok ? response.json() : null).then(data => data && setForm(current => ({ ...current, ...data, apiKey: "" }))); }, []);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm(current => ({ ...current, [key]: value })); }
  async function save() { setBusy(true); setStatus(""); const response = await fetch("/api/admin/ai-settings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); setBusy(false); setStatus(response.ok ? "Configuration saved securely." : data.error || "Unable to save."); if (response.ok) update("apiKey", ""); }
  async function test() { setBusy(true); setStatus("Testing the configured provider…"); const response = await fetch("/api/ai/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ messages: [{ role: "user", content: "Reply with one short sentence describing Mehedi’s portfolio." }] }) }); const data = await response.json(); setBusy(false); setStatus(!response.ok ? "Provider test failed." : data.provider === "local" ? "The configured provider failed, so the local fallback answered. Replace the API key and test again." : `Provider connected successfully via ${data.provider}: ${data.message}`); }

  return <div className="admin-page admin-page-narrow"><header className="admin-page-header"><div><div className="admin-kicker">Operations / Assistant</div><h1>AI configuration</h1><p>Provider routing, behavior and spend controls. Secrets never return to the browser.</p></div><Bot size={25} strokeWidth={1.3} /></header>
    <section className="admin-panel admin-settings-panel"><div className="admin-section-heading"><span>01</span><div><h2>Provider routing</h2><p>Choose the primary model and securely replace its key.</p></div></div>
      <div className="admin-form-grid"><label className="admin-field"><span>Active provider</span><select value={form.activeProvider} onChange={event => update("activeProvider", event.target.value as Form["activeProvider"])} className="admin-input"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option></select></label><label className="admin-field"><span>Model</span><input value={form.model} onChange={event => update("model", event.target.value)} className="admin-input" /></label>
      <label className="admin-field admin-field-wide"><span>API key</span><input value={form.apiKey} onChange={event => update("apiKey", event.target.value)} type="password" className="admin-input" placeholder="Only enter a value to replace the saved key" autoComplete="new-password" /></label>
      <label className="admin-field admin-field-wide"><span>System prompt</span><textarea value={form.systemPrompt} onChange={event => update("systemPrompt", event.target.value)} className="admin-input admin-textarea admin-textarea-tall" /></label></div>
    </section>
    <section className="admin-panel admin-settings-panel"><div className="admin-section-heading"><span>02</span><div><h2>Response controls</h2><p>Keep output focused and usage predictable.</p></div></div><div className="admin-form-grid admin-form-grid-three"><label className="admin-field"><span>Temperature</span><input value={form.temperature} onChange={event => update("temperature", Number(event.target.value))} className="admin-input" type="number" min="0" max="2" step="0.1" /></label><label className="admin-field"><span>Max tokens</span><input value={form.maxTokens} onChange={event => update("maxTokens", Number(event.target.value))} className="admin-input" type="number" /></label><label className="admin-field"><span>Monthly limit</span><input value={form.monthlyLimit} onChange={event => update("monthlyLimit", Number(event.target.value))} className="admin-input" type="number" /></label></div>
      <div className="admin-switch-grid"><label><input type="checkbox" checked={form.leadQualification} onChange={event => update("leadQualification", event.target.checked)} /><span><strong>Lead qualification</strong><small>Score portfolio conversations</small></span></label><label><input type="checkbox" checked={form.bookingEnabled} onChange={event => update("bookingEnabled", event.target.checked)} /><span><strong>Appointment booking</strong><small>Offer next-step scheduling</small></span></label><label><input type="checkbox" checked={form.fallbackEnabled} onChange={event => update("fallbackEnabled", event.target.checked)} /><span><strong>Fallback providers</strong><small>Route around provider failure</small></span></label></div>
    </section>
    <div className="admin-action-bar"><div>{status || "Configuration is encrypted before storage."}</div><button onClick={test} disabled={busy} className="admin-button" type="button"><TestTube2 size={15} />Test</button><button onClick={save} disabled={busy} className="admin-button admin-button-primary" type="button">{busy ? <LoaderCircle className="animate-spin" size={15} /> : <Save size={15} />}Save changes</button></div>
  </div>;
}
